In [3]:
import pandas as pd
import numpy as np 
import PyPDF2
import csv

In [1]:
import PyPDF2
import csv

def pdf_to_csv(pdf_path, csv_path):
    try:
        with open(pdf_path, 'rb') as pdf_file:
            pdf_reader = PyPDF2.PdfReader(pdf_file)
            num_pages = len(pdf_reader.pages)

            with open(csv_path, 'w', encoding='utf-8', newline='') as csv_file:
                csv_writer = csv.writer(csv_file)
                csv_writer.writerow(['Slide Number', 'Content'])

                for page_num in range(num_pages):
                    page = pdf_reader.pages[page_num]
                    content = page.extract_text()
                    csv_writer.writerow([page_num + 1, content])

        print(f'Successfully exported PDF content to CSV. CSV saved to: {csv_path}')

    except Exception as e:
        print(f'Error: {e}')

# Example usage
pdf_file_path = 'dbs-8.pdf'
csv_file_path = 'slide_content_8.csv'
pdf_to_csv(pdf_file_path, csv_file_path)

Successfully exported PDF content to CSV. CSV saved to: slide_content_8.csv

In [4]:
dt = pd.read_csv("slide_content_8.csv")
dt['Slide Number'] = "PDF-8, Pg" + dt['Slide Number'].astype(str)
dt

   Slide Number                                            Content
0    PDF-8, Pg1    Part VIII\nTransactions, Integrity and Triggers
1    PDF-8, Pg2  Transactions, Integrity and Triggers\nTransact...
2    PDF-8, Pg3  Transactions, Integrity and Triggers\nTransact...
3    PDF-8, Pg4  Transactions, Integrity and Triggers\nTransact...
4    PDF-8, Pg5  Transactions, Integrity and Triggers\nTransact...
..          ...                                                ...
64  PDF-8, Pg65  Transactions, Integrity and Triggers Summary\n...
65  PDF-8, Pg66  Transactions, Integrity and Triggers Summary\n...
66  PDF-8, Pg67  Transactions, Integrity and Triggers Summary\n...
67  PDF-8, Pg68  Transactions, Integrity and Triggers Summary\n...
68  PDF-8, Pg69  Transactions, Integrity and Triggers Summary\n...

[69 rows x 2 columns]

In [5]:
df = pd.read_csv('slide_info.csv')
df

     Slide Number                                            Content
0      PDF-2, Pg1     Part II\nRelational Databases – Data as Tables
1      PDF-2, Pg2  Relational Databases – Data as Tables\nRelatio...
2      PDF-2, Pg3  Relational Databases – Data as Tables\nRelatio...
3      PDF-2, Pg4  Relational Databases – Data as Tables\nRelatio...
4      PDF-2, Pg5  Relational Databases – Data as Tables\nRelatio...
..            ...                                                ...
162  PDF-6, Pg105  The Relational Query Language SQL History and ...
163  PDF-6, Pg106  The Relational Query Language SQL History and ...
164  PDF-6, Pg107  The Relational Query Language SQL History and ...
165  PDF-6, Pg108  The Relational Query Language SQL History and ...
166  PDF-6, Pg109  The Relational Query Language SQL History and ...

[167 rows x 2 columns]

In [7]:
slides = pd.concat([df, dt], ignore_index=True)
slides

    Slide Number                                            Content
0     PDF-2, Pg1     Part II\nRelational Databases – Data as Tables
1     PDF-2, Pg2  Relational Databases – Data as Tables\nRelatio...
2     PDF-2, Pg3  Relational Databases – Data as Tables\nRelatio...
3     PDF-2, Pg4  Relational Databases – Data as Tables\nRelatio...
4     PDF-2, Pg5  Relational Databases – Data as Tables\nRelatio...
..           ...                                                ...
231  PDF-8, Pg65  Transactions, Integrity and Triggers Summary\n...
232  PDF-8, Pg66  Transactions, Integrity and Triggers Summary\n...
233  PDF-8, Pg67  Transactions, Integrity and Triggers Summary\n...
234  PDF-8, Pg68  Transactions, Integrity and Triggers Summary\n...
235  PDF-8, Pg69  Transactions, Integrity and Triggers Summary\n...

[236 rows x 2 columns]

In [8]:
csv_filename = 'slides.csv'
slides.to_csv(csv_filename, index=False)